import { Platform, PlatformColor } from "react-native";

const ios = Platform.OS === "ios";

export const Semantic = {
  background:         ios ? PlatformColor("systemBackground")                    : "#F2F2F7",
  surface:            ios ? PlatformColor("secondarySystemBackground")           : "#FFFFFF",
  surfaceAlt:         ios ? PlatformColor("tertiarySystemBackground")            : "#EFEFF4",
  grouped:            ios ? PlatformColor("systemGroupedBackground")             : "#F2F2F7",
  groupedSurface:     ios ? PlatformColor("secondarySystemGroupedBackground")    : "#FFFFFF",
  groupedSurfaceAlt:  ios ? PlatformColor("tertiarySystemGroupedBackground")     : "#F2F2F7",
  label:              ios ? PlatformColor("label")                               : "#000000",
  labelSecondary:     ios ? PlatformColor("secondaryLabel")                      : "#6B6B72",
  labelTertiary:      ios ? PlatformColor("tertiaryLabel")                       : "#AEAEB2",
  labelQuaternary:    ios ? PlatformColor("quaternaryLabel")                     : "#C7C7CC",
  separator:          ios ? PlatformColor("separator")                           : "#C6C6C8",
  opaqueSeparator:    ios ? PlatformColor("opaqueSeparator")                     : "#C6C6C8",
  fill:               ios ? PlatformColor("systemFill")                          : "#78788033",
  fillSecondary:      ios ? PlatformColor("secondarySystemFill")                 : "#78788029",
  fillTertiary:       ios ? PlatformColor("tertiarySystemFill")                  : "#7676801E",
  fillQuaternary:     ios ? PlatformColor("quaternarySystemFill")                : "#74748014",
  systemRed:          ios ? PlatformColor("systemRed")                           : "#FF3B30",
  systemOrange:       ios ? PlatformColor("systemOrange")                        : "#FF9500",
  systemYellow:       ios ? PlatformColor("systemYellow")                        : "#FFCC00",
  systemGreen:        ios ? PlatformColor("systemGreen")                         : "#34C759",
  systemTeal:         ios ? PlatformColor("systemTeal")                          : "#30B0C7",
  systemBlue:         ios ? PlatformColor("systemBlue")                          : "#007AFF",
  systemIndigo:       ios ? PlatformColor("systemIndigo")                        : "#5856D6",
  systemPurple:       ios ? PlatformColor("systemPurple")                        : "#AF52DE",
  systemPink:         ios ? PlatformColor("systemPink")                          : "#FF2D55",
  systemGray:         ios ? PlatformColor("systemGray")                          : "#8E8E93",
  systemGray2:        ios ? PlatformColor("systemGray2")                         : "#AEAEB2",
  systemGray3:        ios ? PlatformColor("systemGray3")                         : "#C7C7CC",
  systemGray4:        ios ? PlatformColor("systemGray4")                         : "#D1D1D6",
  systemGray5:        ios ? PlatformColor("systemGray5")                         : "#E5E5EA",
  systemGray6:        ios ? PlatformColor("systemGray6")                         : "#F2F2F7",
  link:               ios ? PlatformColor("link")                                : "#007AFF",
  placeholderText:    ios ? PlatformColor("placeholderText")                     : "#C7C7CD",
};
